//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatchVideoEncoder {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.24")]
        public string NeroAaacDefaultQuality {
            get {
                return ((string)(this["NeroAaacDefaultQuality"]));
            }
            set {
                this["NeroAaacDefaultQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public string X265DefaultCrf {
            get {
                return ((string)(this["X265DefaultCrf"]));
            }
            set {
                this["X265DefaultCrf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("medium")]
        public string defaultVideoPreset {
            get {
                return ((string)(this["defaultVideoPreset"]));
            }
            set {
                this["defaultVideoPreset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ultrafast,superfast,veryfast,faster,fast,medium,slow,slower,veryslow")]
        public string X265Presets {
            get {
                return ((string)(this["X265Presets"]));
            }
            set {
                this["X265Presets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".avi,.flv,.mp4,.mkv,.mpg,.vob,.wmv,.webm")]
        public string SupportedFileExtensions {
            get {
                return ((string)(this["SupportedFileExtensions"]));
            }
            set {
                this["SupportedFileExtensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_")]
        public string OutFileSuffix {
            get {
                return ((string)(this["OutFileSuffix"]));
            }
            set {
                this["OutFileSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("720")]
        public int xResLimit {
            get {
                return ((int)(this["xResLimit"]));
            }
            set {
                this["xResLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("480")]
        public int yResLimit {
            get {
                return ((int)(this["yResLimit"]));
            }
            set {
                this["yResLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OutputDirectory {
            get {
                return ((string)(this["OutputDirectory"]));
            }
            set {
                this["OutputDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>No Filter, </string>
  <string>Light Denoise Filter,hqdn3d=2.0:1.0:2.0:3.0</string>
  <string>Medium Denoise Filter,hqdn3d=4.0:3.0:6.0:4.5</string>
  <string>Strong Denoise Filter,hqdn3d=7.0:7.0:5.0:5.0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection NoiseFilters {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["NoiseFilters"]));
            }
            set {
                this["NoiseFilters"] = value;
            }
        }
    }
}
