
name: .NET Framework Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: BatchVideoEncoder.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Add MSBuild to PATH
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # Restore NuGet packages
    - name: Restore NuGet packages
      run: nuget restore $env:Solution_Name

    # Build the solution
    - name: Build
      run: msbuild $env:Solution_Name /p:Configuration=${{ matrix.configuration }} /p:Platform="Any CPU"

    # Upload build output as artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BatchVideoEncoder-${{ matrix.configuration }}
        path: BatchVideoEncoder\bin\${{ matrix.configuration }}\
